title: Go兴趣小组
author: busgo
email: 466862016@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  Go语言相关技术栈、开源项目以及Go语言相关最新资讯.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /busgo.github.com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Go兴趣小组
  tagline: 一群Go语言爱好者聚集地
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: busgo
    github:  busgo
    linkedIn: in/busgo
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
